org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# JBR de Android Studio: evita depender de que JAVA_HOME esté fijado en cada sesión.
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
