// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAssign.Infrastructure.Persistence;

#nullable disable

namespace SmartAssign.Infrastructure.Persistence.Migraciones
{
    [DbContext(typeof(SmartAssignDbContext))]
    [Migration("20260809231132_MotorDeValidacion")]
    partial class MotorDeValidacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartAssign.Domain.Entities.Asignacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AsignadoPor")
                        .HasColumnType("int")
                        .HasColumnName("asignado_por");

                    b.Property<bool>("CedePerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("cede_perfil");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fin");

                    b.Property<DateTime>("Inicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("inicio")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("JornadaLineaId")
                        .HasColumnType("int")
                        .HasColumnName("jornada_linea_id");

                    b.Property<long?>("JustificacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("justificacion_id");

                    b.Property<string>("MotivoFin")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("motivo_fin");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("origen");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int")
                        .HasColumnName("personal_id");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int")
                        .HasColumnName("puesto_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int?>("TitularOriginalId")
                        .HasColumnType("int")
                        .HasColumnName("titular_original_id");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoPor");

                    b.HasIndex("JornadaLineaId");

                    b.HasIndex("JustificacionId");

                    b.HasIndex("PersonalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Asig_personal_activo")
                        .HasFilter("[fin] IS NULL");

                    b.HasIndex("PuestoId")
                        .IsUnique()
                        .HasDatabaseName("UX_Asig_puesto_activo")
                        .HasFilter("[fin] IS NULL");

                    b.HasIndex("TitularOriginalId");

                    b.ToTable("Asignacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Asig_fin", "fin IS NULL OR fin >= inicio");

                            t.HasCheckConstraint("CK_Asig_origen", "origen IN ('barrido_automatico','manual_supervisor','relevo','reasignacion_relevado','extraccion_inversa','intervencion_coordinador','cobertura_vacante_critica')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("accion");

                    b.Property<string>("CodigoRechazo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("codigo_rechazo");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_antes");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_despues");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("device_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("entidad");

                    b.Property<long?>("EntidadId")
                        .HasColumnType("bigint")
                        .HasColumnName("entidad_id");

                    b.Property<long?>("JustificacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("justificacion_id");

                    b.Property<byte?>("LineaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_id");

                    b.Property<DateTime>("OcurridoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ocurrido_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("PersonalId")
                        .HasColumnType("int")
                        .HasColumnName("personal_id");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("resultado");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("rol");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("CodigoRechazo", "OcurridoEn")
                        .HasDatabaseName("IX_Aud_rechazo")
                        .HasFilter("[resultado] = 'RECHAZO'");

                    b.HasIndex("LineaId", "OcurridoEn")
                        .HasDatabaseName("IX_Aud_linea");

                    b.HasIndex("PersonalId", "OcurridoEn")
                        .HasDatabaseName("IX_Aud_persona");

                    b.ToTable("Auditoria", null, t =>
                        {
                            t.HasCheckConstraint("CK_Aud_resultado", "resultado IN ('OK','RECHAZO')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.AusenciaJustificada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int")
                        .HasColumnName("personal_id");

                    b.Property<int>("RegistradoPor")
                        .HasColumnType("int")
                        .HasColumnName("registrado_por");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("AusenciaJustificada", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ausencia_tipo", "tipo IN ('vacaciones','permiso','cita_medica','subsidio','accidente_laboral','otro')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CapacidadFisica", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CapacidadFisica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            Codigo = "levantar_carga",
                            Nombre = "Levantar carga"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            Codigo = "bipedestacion_prolongada",
                            Nombre = "Bipedestación prolongada"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            Codigo = "movimiento_repetitivo_mano",
                            Nombre = "Movimiento repetitivo de mano"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            Codigo = "esfuerzo_lumbar",
                            Nombre = "Esfuerzo lumbar"
                        },
                        new
                        {
                            Id = (short)5,
                            Activo = true,
                            Codigo = "exposicion_quimicos",
                            Nombre = "Exposición a químicos"
                        },
                        new
                        {
                            Id = (short)6,
                            Activo = true,
                            Codigo = "trabajo_en_altura",
                            Nombre = "Trabajo en altura"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CategoriaParo", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriaParo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            Nombre = "Mecánico"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            Nombre = "Eléctrico"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            Nombre = "Calidad"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            Nombre = "Falta de material"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CausaParo", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<short>("CategoriaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId", "Nombre")
                        .IsUnique();

                    b.ToTable("CausaParo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            CategoriaId = (short)1,
                            Nombre = "Avería de máquina"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            CategoriaId = (short)1,
                            Nombre = "Ajuste mecánico"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            CategoriaId = (short)2,
                            Nombre = "Corte de energía"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            CategoriaId = (short)3,
                            Nombre = "Producto fuera de especificación"
                        },
                        new
                        {
                            Id = (short)5,
                            Activo = true,
                            CategoriaId = (short)4,
                            Nombre = "Desabasto de insumo"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.DispositivoPush", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("device_id");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("android")
                        .HasColumnName("plataforma");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("push_token");

                    b.Property<DateTime>("RegistradoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("registrado_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("revocado_en");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_DispositivoPush");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Push_activo")
                        .HasFilter("[revocado_en] IS NULL");

                    b.ToTable("DispositivoPush", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.JornadaLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrancadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("arrancado_en");

                    b.Property<DateTime?>("CerradoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("cerrado_en");

                    b.Property<byte>("LineaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("VentanaArranqueFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("ventana_arranque_fin");

                    b.HasKey("Id");

                    b.HasIndex("LineaId")
                        .IsUnique()
                        .HasDatabaseName("UX_JornadaLinea_abierta")
                        .HasFilter("[cerrado_en] IS NULL");

                    b.ToTable("JornadaLinea", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.JustificacionExcepcion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creada_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<short>("MotivoId")
                        .HasColumnType("smallint")
                        .HasColumnName("motivo_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("texto");

                    b.Property<string>("TipoExcepcion")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("tipo_excepcion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("MotivoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("JustificacionExcepcion", null, t =>
                        {
                            t.HasCheckConstraint("CK_JE_texto", "LEN(LTRIM(RTRIM(texto))) >= 10");

                            t.HasCheckConstraint("CK_JE_tipo", "tipo_excepcion IN ('movimiento_fuera_de_flujo','saltar_ventana_arranque','forzar_cierre_turno','extraccion_operador_b','forzar_bajo_piso_seguridad','cancelar_transito','asignacion_liderazgo')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Linea", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("Id");

                    b.Property<bool>("ActivaHoy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("activa_hoy");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("EsBolson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("es_bolson");

                    b.Property<short?>("MinimoOperarios")
                        .HasColumnType("smallint")
                        .HasColumnName("minimo_operarios");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("inactiva")
                        .HasColumnName("situacion");

                    b.Property<int?>("SupervisorActualId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_actual");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EsBolson")
                        .IsUnique()
                        .HasDatabaseName("UX_Linea_bolson")
                        .HasFilter("[es_bolson] = 1");

                    b.HasIndex("SupervisorActualId")
                        .IsUnique()
                        .HasDatabaseName("UX_Linea_supervisor")
                        .HasFilter("[supervisor_actual] IS NOT NULL");

                    b.ToTable("Linea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Linea_situacion", "situacion IN ('inactiva','activa','en_arranque','en_produccion','en_paro','en_limpieza')");
                        });

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            ActivaHoy = false,
                            Codigo = "L1",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 1",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)2,
                            ActivaHoy = false,
                            Codigo = "L2",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 2",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)3,
                            ActivaHoy = false,
                            Codigo = "L3",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 3",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)4,
                            ActivaHoy = false,
                            Codigo = "L4",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 4",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)5,
                            ActivaHoy = false,
                            Codigo = "L5",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 5",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)6,
                            ActivaHoy = false,
                            Codigo = "L6",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 6",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)7,
                            ActivaHoy = false,
                            Codigo = "L7",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 7",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)8,
                            ActivaHoy = false,
                            Codigo = "L8",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = true,
                            Nombre = "Línea 8",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)9,
                            ActivaHoy = false,
                            Codigo = "L9",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 9",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)10,
                            ActivaHoy = false,
                            Codigo = "L10",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 10",
                            Situacion = "inactiva"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.MotivoExcepcion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MotivoExcepcion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            Nombre = "Acuerdo directo con el trabajador"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            Nombre = "Extracción de Operador B por vacante crítica"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            Nombre = "Forzar cierre de turno"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            Nombre = "Forzar por debajo del piso de seguridad"
                        },
                        new
                        {
                            Id = (short)5,
                            Activo = true,
                            Nombre = "Saltar ventana de arranque"
                        },
                        new
                        {
                            Id = (short)6,
                            Activo = true,
                            Nombre = "Cancelar tránsito caducado"
                        },
                        new
                        {
                            Id = (short)7,
                            Activo = true,
                            Nombre = "Asignación manual de personal de liderazgo"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.MotivoRechazoRecepcion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MotivoRechazoRecepcion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            Nombre = "La persona no se presentó"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            Nombre = "Persona incorrecta"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            Nombre = "El puesto ya no requiere relevo"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Parametro", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("ModificadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("modificado_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("valor");

                    b.HasKey("Clave");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Parametro", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("categoria");

                    b.Property<bool>("DobleTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("doble_turno");

                    b.Property<string>("Ficha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ficha");

                    b.Property<byte?>("LineaFisicaActual")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_fisica_actual");

                    b.Property<byte?>("LineaHabitual")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_habitual");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("OrigenDato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("real")
                        .HasColumnName("origen_dato");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Sexo")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("sexo");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("fuera_de_turno")
                        .HasColumnName("situacion");

                    b.HasKey("Id");

                    b.HasIndex("Ficha")
                        .IsUnique();

                    b.HasIndex("LineaFisicaActual");

                    b.HasIndex("LineaHabitual");

                    b.HasIndex("Situacion", "LineaFisicaActual")
                        .HasDatabaseName("IX_Personal_disponible")
                        .HasFilter("[activo] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Situacion", "LineaFisicaActual"), new[] { "Ficha", "NombreCompleto", "Categoria" });

                    b.ToTable("Personal", null, t =>
                        {
                            t.HasCheckConstraint("CK_Personal_categoria", "categoria IN ('operario','operador_a','operador_b','operador_c','averiero','liderazgo')");

                            t.HasCheckConstraint("CK_Personal_origen_dato", "origen_dato IN ('real','simulado','simulado_categoria')");

                            t.HasCheckConstraint("CK_Personal_situacion", "situacion IN ('fuera_de_turno','presente_sin_asignar','asignado','en_transito','en_bolson','retirado_temporal','ausente_justificado')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PrioridadLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CambiadoPor")
                        .HasColumnType("int")
                        .HasColumnName("cambiado_por");

                    b.Property<byte>("LineaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_id");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint")
                        .HasColumnName("orden");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id");

                    b.HasIndex("LineaId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prioridad_vigente")
                        .HasFilter("[vigente_hasta] IS NULL");

                    b.HasIndex("Orden")
                        .IsUnique()
                        .HasDatabaseName("UX_Prioridad_orden_vigente")
                        .HasFilter("[vigente_hasta] IS NULL");

                    b.ToTable("PrioridadLinea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prioridad_orden", "orden BETWEEN 1 AND 10");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CambiadoPor = 0,
                            LineaId = (byte)4,
                            Orden = (byte)1,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CambiadoPor = 0,
                            LineaId = (byte)1,
                            Orden = (byte)2,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CambiadoPor = 0,
                            LineaId = (byte)2,
                            Orden = (byte)3,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CambiadoPor = 0,
                            LineaId = (byte)6,
                            Orden = (byte)4,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CambiadoPor = 0,
                            LineaId = (byte)7,
                            Orden = (byte)5,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CambiadoPor = 0,
                            LineaId = (byte)5,
                            Orden = (byte)6,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CambiadoPor = 0,
                            LineaId = (byte)3,
                            Orden = (byte)7,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CambiadoPor = 0,
                            LineaId = (byte)8,
                            Orden = (byte)8,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CambiadoPor = 0,
                            LineaId = (byte)9,
                            Orden = (byte)9,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CambiadoPor = 0,
                            LineaId = (byte)10,
                            Orden = (byte)10,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.ProximidadLinea", b =>
                {
                    b.Property<byte>("LineaOrigenId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_origen");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint")
                        .HasColumnName("orden");

                    b.Property<byte>("LineaDestinoId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_destino");

                    b.HasKey("LineaOrigenId", "Orden");

                    b.HasIndex("LineaDestinoId");

                    b.HasIndex("LineaOrigenId", "LineaDestinoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Proximidad");

                    b.ToTable("ProximidadLinea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Proximidad_distinta", "linea_origen <> linea_destino");

                            t.HasCheckConstraint("CK_Proximidad_orden", "orden BETWEEN 1 AND 9");
                        });

                    b.HasData(
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CategoriaTitular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("categoria_titular");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<short?>("HorasEnPuesto")
                        .HasColumnType("smallint")
                        .HasColumnName("horas_en_puesto");

                    b.Property<short?>("HorasRecuperacion")
                        .HasColumnType("smallint")
                        .HasColumnName("horas_recuperacion");

                    b.Property<byte>("LineaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_id");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre_puesto");

                    b.Property<string>("PerfilRequerido")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("perfil_requerido");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SexoPreferente")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("sexo_preferente");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo");

                    b.Property<short?>("TipoActividadId")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_actividad_id");

                    b.Property<int?>("TitularId")
                        .HasColumnType("int")
                        .HasColumnName("titular_id");

                    b.Property<short?>("UmbralCriticoHoras")
                        .HasColumnType("smallint")
                        .HasColumnName("umbral_critico_horas");

                    b.HasKey("Id");

                    b.HasIndex("TipoActividadId");

                    b.HasIndex("TitularId");

                    b.HasIndex("LineaId", "Codigo")
                        .IsUnique();

                    b.ToTable("Puesto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Puesto_categoria", "tipo = 'fijo' OR categoria_titular IS NULL");

                            t.HasCheckConstraint("CK_Puesto_tipo", "tipo IN ('fijo','rotativo')");

                            t.HasCheckConstraint("CK_Puesto_umbrales", "umbral_critico_horas IS NULL OR horas_en_puesto IS NULL OR umbral_critico_horas > horas_en_puesto");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PuestoCapacidad", b =>
                {
                    b.Property<int>("PuestoId")
                        .HasColumnType("int")
                        .HasColumnName("puesto_id");

                    b.Property<short>("CapacidadId")
                        .HasColumnType("smallint")
                        .HasColumnName("capacidad_id");

                    b.HasKey("PuestoId", "CapacidadId");

                    b.HasIndex("CapacidadId");

                    b.ToTable("PuestoCapacidad", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PuestoSku", b =>
                {
                    b.Property<int>("PuestoId")
                        .HasColumnType("int")
                        .HasColumnName("puesto_id");

                    b.Property<int>("SkuId")
                        .HasColumnType("int")
                        .HasColumnName("sku_id");

                    b.HasKey("PuestoId", "SkuId");

                    b.HasIndex("SkuId");

                    b.ToTable("PuestoSKU", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.RestriccionMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("CapacidadId")
                        .HasColumnType("smallint")
                        .HasColumnName("capacidad_id");

                    b.Property<DateOnly>("FechaDictamen")
                        .HasColumnType("date")
                        .HasColumnName("fecha_dictamen");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("fuente");

                    b.Property<string>("Observacion")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("observacion");

                    b.Property<string>("OrigenDato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("simulado")
                        .HasColumnName("origen_dato");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int")
                        .HasColumnName("personal_id");

                    b.Property<DateTime>("RegistradoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("registrado_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("RegistradoPor")
                        .HasColumnType("int")
                        .HasColumnName("registrado_por");

                    b.HasKey("Id");

                    b.HasIndex("CapacidadId");

                    b.HasIndex("RegistradoPor");

                    b.HasIndex("PersonalId", "CapacidadId")
                        .HasDatabaseName("IX_RM_vigentes");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PersonalId", "CapacidadId"), new[] { "FechaInicio", "FechaFin" });

                    b.ToTable("RestriccionMedica", null, t =>
                        {
                            t.HasCheckConstraint("CK_RM_origen_dato", "origen_dato IN ('real','simulado')");

                            t.HasCheckConstraint("CK_RM_vigencia", "fecha_fin IS NULL OR fecha_fin >= fecha_inicio");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.SesionDispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("EmitidoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("emitido_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("expira_en");

                    b.Property<byte[]>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("revocado_en");

                    b.Property<DateTime>("UltimaActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ultima_actividad")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DeviceId")
                        .HasDatabaseName("IX_Sesion_activa")
                        .HasFilter("[revocado_en] IS NULL");

                    b.ToTable("SesionDispositivo", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("RitmoTeoricoHora")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ritmo_teorico_hora");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("SKU", null, t =>
                        {
                            t.HasCheckConstraint("CK_SKU_ritmo", "ritmo_teorico_hora > 0");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.TipoActividad", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoActividad", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.UltimaTareaJornada", b =>
                {
                    b.Property<int>("PersonalId")
                        .HasColumnType("int")
                        .HasColumnName("personal_id");

                    b.Property<DateOnly>("DiaOperacion")
                        .HasColumnType("date")
                        .HasColumnName("dia_operacion");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int")
                        .HasColumnName("puesto_id");

                    b.Property<DateTime>("RegistradoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("registrado_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<short>("TipoActividadId")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_actividad_id");

                    b.HasKey("PersonalId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("TipoActividadId");

                    b.ToTable("UltimaTareaJornada", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<byte>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("OrigenIdentidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("local")
                        .HasColumnName("origen_identidad");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)")
                        .HasColumnName("password_salt");

                    b.Property<int?>("PersonalId")
                        .HasColumnType("int")
                        .HasColumnName("personal_id");

                    b.Property<byte[]>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)")
                        .HasColumnName("pin_hash");

                    b.Property<byte[]>("PinSalt")
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)")
                        .HasColumnName("pin_salt");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_origen", "origen_identidad IN ('ad','local')");

                            t.HasCheckConstraint("CK_Usuario_rol", "rol IN ('coordinador','supervisor')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Asignacion", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AsignadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.JornadaLinea", "JornadaLinea")
                        .WithMany()
                        .HasForeignKey("JornadaLineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.JustificacionExcepcion", null)
                        .WithMany()
                        .HasForeignKey("JustificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartAssign.Domain.Entities.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Personal", null)
                        .WithMany()
                        .HasForeignKey("TitularOriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("JornadaLinea");

                    b.Navigation("Personal");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", null)
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartAssign.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.AusenciaJustificada", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CausaParo", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.CategoriaParo", "Categoria")
                        .WithMany("Causas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.DispositivoPush", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.JornadaLinea", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Linea");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.JustificacionExcepcion", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.MotivoExcepcion", "Motivo")
                        .WithMany()
                        .HasForeignKey("MotivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Motivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Linea", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("SupervisorActualId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Parametro", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Personal", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "LineaFisicaActualNav")
                        .WithMany()
                        .HasForeignKey("LineaFisicaActual")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartAssign.Domain.Entities.Linea", "LineaHabitualNav")
                        .WithMany()
                        .HasForeignKey("LineaHabitual")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LineaFisicaActualNav");

                    b.Navigation("LineaHabitualNav");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PrioridadLinea", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Linea");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.ProximidadLinea", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "LineaDestino")
                        .WithMany()
                        .HasForeignKey("LineaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Linea", "LineaOrigen")
                        .WithMany()
                        .HasForeignKey("LineaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LineaDestino");

                    b.Navigation("LineaOrigen");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Puesto", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.TipoActividad", "TipoActividad")
                        .WithMany()
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartAssign.Domain.Entities.Personal", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Linea");

                    b.Navigation("TipoActividad");

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PuestoCapacidad", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.CapacidadFisica", "Capacidad")
                        .WithMany()
                        .HasForeignKey("CapacidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capacidad");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PuestoSku", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puesto");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.RestriccionMedica", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.CapacidadFisica", "Capacidad")
                        .WithMany()
                        .HasForeignKey("CapacidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capacidad");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.SesionDispositivo", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.UltimaTareaJornada", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.TipoActividad", "TipoActividad")
                        .WithMany()
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Puesto");

                    b.Navigation("TipoActividad");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CategoriaParo", b =>
                {
                    b.Navigation("Causas");
                });
#pragma warning restore 612, 618
        }
    }
}
