// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAssign.Infrastructure.Persistence;

#nullable disable

namespace SmartAssign.Infrastructure.Persistence.Migraciones
{
    [DbContext(typeof(SmartAssignDbContext))]
    [Migration("20260809180733_InicialEstructura")]
    partial class InicialEstructura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartAssign.Domain.Entities.CapacidadFisica", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CapacidadFisica", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CategoriaParo", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriaParo", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CausaParo", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<short>("CategoriaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId", "Nombre")
                        .IsUnique();

                    b.ToTable("CausaParo", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Linea", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("Id");

                    b.Property<bool>("ActivaHoy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("activa_hoy");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EsBolson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("es_bolson");

                    b.Property<short?>("MinimoOperarios")
                        .HasColumnType("smallint")
                        .HasColumnName("minimo_operarios");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("inactiva")
                        .HasColumnName("situacion");

                    b.Property<int?>("SupervisorActualId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_actual");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EsBolson")
                        .IsUnique()
                        .HasDatabaseName("UX_Linea_bolson")
                        .HasFilter("[es_bolson] = 1");

                    b.HasIndex("SupervisorActualId")
                        .IsUnique()
                        .HasDatabaseName("UX_Linea_supervisor")
                        .HasFilter("[supervisor_actual] IS NOT NULL");

                    b.ToTable("Linea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Linea_situacion", "situacion IN ('inactiva','activa','en_arranque','en_produccion','en_paro','en_limpieza')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.MotivoExcepcion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MotivoExcepcion", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.MotivoRechazoRecepcion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MotivoRechazoRecepcion", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PrioridadLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CambiadoPor")
                        .HasColumnType("int")
                        .HasColumnName("cambiado_por");

                    b.Property<byte>("LineaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_id");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint")
                        .HasColumnName("orden");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id");

                    b.HasIndex("LineaId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prioridad_vigente")
                        .HasFilter("[vigente_hasta] IS NULL");

                    b.HasIndex("Orden")
                        .IsUnique()
                        .HasDatabaseName("UX_Prioridad_orden_vigente")
                        .HasFilter("[vigente_hasta] IS NULL");

                    b.ToTable("PrioridadLinea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prioridad_orden", "orden BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.ProximidadLinea", b =>
                {
                    b.Property<byte>("LineaOrigenId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_origen");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint")
                        .HasColumnName("orden");

                    b.Property<byte>("LineaDestinoId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_destino");

                    b.HasKey("LineaOrigenId", "Orden");

                    b.HasIndex("LineaDestinoId");

                    b.HasIndex("LineaOrigenId", "LineaDestinoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Proximidad");

                    b.ToTable("ProximidadLinea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Proximidad_distinta", "linea_origen <> linea_destino");

                            t.HasCheckConstraint("CK_Proximidad_orden", "orden BETWEEN 1 AND 9");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CategoriaTitular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("categoria_titular");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<short?>("HorasEnPuesto")
                        .HasColumnType("smallint")
                        .HasColumnName("horas_en_puesto");

                    b.Property<short?>("HorasRecuperacion")
                        .HasColumnType("smallint")
                        .HasColumnName("horas_recuperacion");

                    b.Property<byte>("LineaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_id");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre_puesto");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SexoPreferente")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("sexo_preferente");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo");

                    b.Property<short?>("TipoActividadId")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_actividad_id");

                    b.HasKey("Id");

                    b.HasIndex("TipoActividadId");

                    b.HasIndex("LineaId", "Codigo")
                        .IsUnique();

                    b.ToTable("Puesto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Puesto_categoria", "(tipo = 'fijo' AND categoria_titular IS NOT NULL) OR (tipo = 'rotativo' AND categoria_titular IS NULL)");

                            t.HasCheckConstraint("CK_Puesto_tipo", "tipo IN ('fijo','rotativo')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PuestoSku", b =>
                {
                    b.Property<int>("PuestoId")
                        .HasColumnType("int")
                        .HasColumnName("puesto_id");

                    b.Property<int>("SkuId")
                        .HasColumnType("int")
                        .HasColumnName("sku_id");

                    b.HasKey("PuestoId", "SkuId");

                    b.HasIndex("SkuId");

                    b.ToTable("PuestoSKU", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("RitmoTeoricoHora")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ritmo_teorico_hora");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("SKU", null, t =>
                        {
                            t.HasCheckConstraint("CK_SKU_ritmo", "ritmo_teorico_hora > 0");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.TipoActividad", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoActividad", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CausaParo", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.CategoriaParo", "Categoria")
                        .WithMany("Causas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PrioridadLinea", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Linea");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.ProximidadLinea", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "LineaDestino")
                        .WithMany()
                        .HasForeignKey("LineaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Linea", "LineaOrigen")
                        .WithMany()
                        .HasForeignKey("LineaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LineaDestino");

                    b.Navigation("LineaOrigen");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Puesto", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.TipoActividad", "TipoActividad")
                        .WithMany()
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Linea");

                    b.Navigation("TipoActividad");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PuestoSku", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puesto");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CategoriaParo", b =>
                {
                    b.Navigation("Causas");
                });
#pragma warning restore 612, 618
        }
    }
}
