// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAssign.Infrastructure.Persistence;

#nullable disable

namespace SmartAssign.Infrastructure.Persistence.Migraciones
{
    [DbContext(typeof(SmartAssignDbContext))]
    partial class SmartAssignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartAssign.Domain.Entities.CapacidadFisica", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CapacidadFisica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            Codigo = "levantar_carga",
                            Nombre = "Levantar carga"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            Codigo = "bipedestacion_prolongada",
                            Nombre = "Bipedestación prolongada"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            Codigo = "movimiento_repetitivo_mano",
                            Nombre = "Movimiento repetitivo de mano"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            Codigo = "esfuerzo_lumbar",
                            Nombre = "Esfuerzo lumbar"
                        },
                        new
                        {
                            Id = (short)5,
                            Activo = true,
                            Codigo = "exposicion_quimicos",
                            Nombre = "Exposición a químicos"
                        },
                        new
                        {
                            Id = (short)6,
                            Activo = true,
                            Codigo = "trabajo_en_altura",
                            Nombre = "Trabajo en altura"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CategoriaParo", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriaParo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            Nombre = "Mecánico"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            Nombre = "Eléctrico"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            Nombre = "Calidad"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            Nombre = "Falta de material"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CausaParo", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<short>("CategoriaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId", "Nombre")
                        .IsUnique();

                    b.ToTable("CausaParo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            CategoriaId = (short)1,
                            Nombre = "Avería de máquina"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            CategoriaId = (short)1,
                            Nombre = "Ajuste mecánico"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            CategoriaId = (short)2,
                            Nombre = "Corte de energía"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            CategoriaId = (short)3,
                            Nombre = "Producto fuera de especificación"
                        },
                        new
                        {
                            Id = (short)5,
                            Activo = true,
                            CategoriaId = (short)4,
                            Nombre = "Desabasto de insumo"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Linea", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("Id");

                    b.Property<bool>("ActivaHoy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("activa_hoy");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("EsBolson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("es_bolson");

                    b.Property<short?>("MinimoOperarios")
                        .HasColumnType("smallint")
                        .HasColumnName("minimo_operarios");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("inactiva")
                        .HasColumnName("situacion");

                    b.Property<int?>("SupervisorActualId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_actual");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EsBolson")
                        .IsUnique()
                        .HasDatabaseName("UX_Linea_bolson")
                        .HasFilter("[es_bolson] = 1");

                    b.HasIndex("SupervisorActualId")
                        .IsUnique()
                        .HasDatabaseName("UX_Linea_supervisor")
                        .HasFilter("[supervisor_actual] IS NOT NULL");

                    b.ToTable("Linea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Linea_situacion", "situacion IN ('inactiva','activa','en_arranque','en_produccion','en_paro','en_limpieza')");
                        });

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            ActivaHoy = false,
                            Codigo = "L1",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 1",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)2,
                            ActivaHoy = false,
                            Codigo = "L2",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 2",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)3,
                            ActivaHoy = false,
                            Codigo = "L3",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 3",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)4,
                            ActivaHoy = false,
                            Codigo = "L4",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 4",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)5,
                            ActivaHoy = false,
                            Codigo = "L5",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 5",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)6,
                            ActivaHoy = false,
                            Codigo = "L6",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 6",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)7,
                            ActivaHoy = false,
                            Codigo = "L7",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 7",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)8,
                            ActivaHoy = false,
                            Codigo = "L8",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = true,
                            Nombre = "Línea 8",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)9,
                            ActivaHoy = false,
                            Codigo = "L9",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 9",
                            Situacion = "inactiva"
                        },
                        new
                        {
                            Id = (byte)10,
                            ActivaHoy = false,
                            Codigo = "L10",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsBolson = false,
                            Nombre = "Línea 10",
                            Situacion = "inactiva"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.MotivoExcepcion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MotivoExcepcion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            Nombre = "Acuerdo directo con el trabajador"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            Nombre = "Extracción de Operador B por vacante crítica"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            Nombre = "Forzar cierre de turno"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            Nombre = "Forzar por debajo del piso de seguridad"
                        },
                        new
                        {
                            Id = (short)5,
                            Activo = true,
                            Nombre = "Saltar ventana de arranque"
                        },
                        new
                        {
                            Id = (short)6,
                            Activo = true,
                            Nombre = "Cancelar tránsito caducado"
                        },
                        new
                        {
                            Id = (short)7,
                            Activo = true,
                            Nombre = "Asignación manual de personal de liderazgo"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.MotivoRechazoRecepcion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MotivoRechazoRecepcion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Activo = true,
                            Nombre = "La persona no se presentó"
                        },
                        new
                        {
                            Id = (short)2,
                            Activo = true,
                            Nombre = "Persona incorrecta"
                        },
                        new
                        {
                            Id = (short)3,
                            Activo = true,
                            Nombre = "El puesto ya no requiere relevo"
                        },
                        new
                        {
                            Id = (short)4,
                            Activo = true,
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PrioridadLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CambiadoPor")
                        .HasColumnType("int")
                        .HasColumnName("cambiado_por");

                    b.Property<byte>("LineaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_id");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint")
                        .HasColumnName("orden");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id");

                    b.HasIndex("LineaId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prioridad_vigente")
                        .HasFilter("[vigente_hasta] IS NULL");

                    b.HasIndex("Orden")
                        .IsUnique()
                        .HasDatabaseName("UX_Prioridad_orden_vigente")
                        .HasFilter("[vigente_hasta] IS NULL");

                    b.ToTable("PrioridadLinea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prioridad_orden", "orden BETWEEN 1 AND 10");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CambiadoPor = 0,
                            LineaId = (byte)4,
                            Orden = (byte)1,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CambiadoPor = 0,
                            LineaId = (byte)1,
                            Orden = (byte)2,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CambiadoPor = 0,
                            LineaId = (byte)2,
                            Orden = (byte)3,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CambiadoPor = 0,
                            LineaId = (byte)6,
                            Orden = (byte)4,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CambiadoPor = 0,
                            LineaId = (byte)7,
                            Orden = (byte)5,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CambiadoPor = 0,
                            LineaId = (byte)5,
                            Orden = (byte)6,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CambiadoPor = 0,
                            LineaId = (byte)3,
                            Orden = (byte)7,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CambiadoPor = 0,
                            LineaId = (byte)8,
                            Orden = (byte)8,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CambiadoPor = 0,
                            LineaId = (byte)9,
                            Orden = (byte)9,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CambiadoPor = 0,
                            LineaId = (byte)10,
                            Orden = (byte)10,
                            VigenteDesde = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.ProximidadLinea", b =>
                {
                    b.Property<byte>("LineaOrigenId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_origen");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint")
                        .HasColumnName("orden");

                    b.Property<byte>("LineaDestinoId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_destino");

                    b.HasKey("LineaOrigenId", "Orden");

                    b.HasIndex("LineaDestinoId");

                    b.HasIndex("LineaOrigenId", "LineaDestinoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Proximidad");

                    b.ToTable("ProximidadLinea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Proximidad_distinta", "linea_origen <> linea_destino");

                            t.HasCheckConstraint("CK_Proximidad_orden", "orden BETWEEN 1 AND 9");
                        });

                    b.HasData(
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)1,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)2,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)3,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)4,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)5,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)6,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)7,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)10
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)9,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)1,
                            LineaDestinoId = (byte)9
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)2,
                            LineaDestinoId = (byte)3
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)3,
                            LineaDestinoId = (byte)6
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)4,
                            LineaDestinoId = (byte)7
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)5,
                            LineaDestinoId = (byte)4
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)6,
                            LineaDestinoId = (byte)2
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)7,
                            LineaDestinoId = (byte)1
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)8,
                            LineaDestinoId = (byte)5
                        },
                        new
                        {
                            LineaOrigenId = (byte)10,
                            Orden = (byte)9,
                            LineaDestinoId = (byte)8
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CategoriaTitular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("categoria_titular");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<short?>("HorasEnPuesto")
                        .HasColumnType("smallint")
                        .HasColumnName("horas_en_puesto");

                    b.Property<short?>("HorasRecuperacion")
                        .HasColumnType("smallint")
                        .HasColumnName("horas_recuperacion");

                    b.Property<byte>("LineaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("linea_id");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre_puesto");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SexoPreferente")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("sexo_preferente");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo");

                    b.Property<short?>("TipoActividadId")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_actividad_id");

                    b.HasKey("Id");

                    b.HasIndex("TipoActividadId");

                    b.HasIndex("LineaId", "Codigo")
                        .IsUnique();

                    b.ToTable("Puesto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Puesto_categoria", "(tipo = 'fijo' AND categoria_titular IS NOT NULL) OR (tipo = 'rotativo' AND categoria_titular IS NULL)");

                            t.HasCheckConstraint("CK_Puesto_tipo", "tipo IN ('fijo','rotativo')");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PuestoSku", b =>
                {
                    b.Property<int>("PuestoId")
                        .HasColumnType("int")
                        .HasColumnName("puesto_id");

                    b.Property<int>("SkuId")
                        .HasColumnType("int")
                        .HasColumnName("sku_id");

                    b.HasKey("PuestoId", "SkuId");

                    b.HasIndex("SkuId");

                    b.ToTable("PuestoSKU", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("RitmoTeoricoHora")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ritmo_teorico_hora");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("SKU", null, t =>
                        {
                            t.HasCheckConstraint("CK_SKU_ritmo", "ritmo_teorico_hora > 0");
                        });
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.TipoActividad", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoActividad", (string)null);
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CausaParo", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.CategoriaParo", "Categoria")
                        .WithMany("Causas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PrioridadLinea", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Linea");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.ProximidadLinea", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "LineaDestino")
                        .WithMany()
                        .HasForeignKey("LineaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Linea", "LineaOrigen")
                        .WithMany()
                        .HasForeignKey("LineaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LineaDestino");

                    b.Navigation("LineaOrigen");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.Puesto", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Linea", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.TipoActividad", "TipoActividad")
                        .WithMany()
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Linea");

                    b.Navigation("TipoActividad");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.PuestoSku", b =>
                {
                    b.HasOne("SmartAssign.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartAssign.Domain.Entities.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puesto");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("SmartAssign.Domain.Entities.CategoriaParo", b =>
                {
                    b.Navigation("Causas");
                });
#pragma warning restore 612, 618
        }
    }
}
